title: "eNATL"
description: >
  eNATL60-TSW-60m & 600m are extractions of a very high resolution oceanic simulation of the North Atlantic performed at MEOM, IGE (FRANCE).
recipes:
  - id: enatl60-blbt02
    object: "eNATL60:eNATL60BLBT02"
  - id: enatl600m-blbt02
    object: "eNATL600:eNATL600BLBT02"

provenance:
  providers:
    - name: "Zenodo"
      description: "Zenodo"
      roles:
        - host
      url: https://zenodo.org/records/10261274
  license: "unknown"
maintainers:
  - name: "Julius Busecke"
    orcid: 0000-0001-8571-865X
    github: jbusecke
  - name: "Charles Stern"
    orcid: 0000-0002-4078-0852
    github: cisaacstern
  - name: "Raphael Hagen"
    orcid: https://orcid.org/0000-0003-1994-1153
    github: norlandrhagen
