title: "LEAP Data Library"
description: >
  eNATL60-TSW-60m is an extraction of a very high resolution oceanic simulation of the North Atlantic performed at MEOM, IGE (FRANCE)
recipes:
  - id: eNATL60_BLBT02
    object: "eNATL60:eNATL60_BLBT02"
  - id: eNATL60_BLBT02_pyramid
    object: "pyramid:pyramid"
provenance:
  providers:
    - name: "Zenodo"
      description: "Zenodo"
      roles:
        - host
      url: https://zenodo.org/records/10261274
    - name: "TBD"
      description: "TODO"
      roles:
        - producer
        - licensor
  license: "unknown"
maintainers:
  - name: "Julius Busecke"
    orcid: 0000-0001-8571-865X
    github: jbusecke
  - name: "Charles Stern"
    orcid: 0000-0002-4078-0852
    github: cisaacstern
