name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
#   schedule:
#     - cron: '0 0 * * *' # Daily “At 00:00” UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Set up conda environment
        uses: mamba-org/provision-with-micromamba@v16
        with:
          micromamba-version: latest
          channel-priority: strict
          environment-file: ci/environment.yaml
          environment-name: leap-data-management
          cache-env: true
          cache-downloads: true
      - name: Validate schema
        run: |
          cd catalog/validator
          python schema.py

      - name: Validate datasets
        run: |
          cd catalog/validator
          python validate.py --path ../datasets

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: consolidated-web-catalog.json
          path: catalog/datasets/consolidated-web-catalog.json

  update-catalog:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up conda environment
        uses: mamba-org/provision-with-micromamba@v16
        with:
          micromamba-version: latest
          channel-priority: strict
          environment-file: ci/environment.yaml
          environment-name: leap-data-management
          cache-env: true
          cache-downloads: true

      - uses: actions/download-artifact@v4
        with:
          name: consolidated-web-catalog.json
          path: catalog/datasets

      - name: Fix formatting
        run: |
          pre-commit install
          git add catalog/datasets/consolidated-web-catalog.json
          # run pre-commit and return 0 to avoid failing the job
          pre-commit run || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "update consolidated-web-catalog.json"
          committer: GitHub <noreply@github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          title: Update catalog
          body: |
            - Updates the consolidated web catalog for changes on `main`
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request

          branch: update-catalog
          delete-branch: true
          reviewers: andersy005